[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Git_jll = "f8c6e375-362e-5223-8a59-34ff63f689eb"
ITensorPkgSkeleton = "3d388ab1-018a-49f4-ae50-18094d5f71ea"

[compat]
Documenter = "1"
Literate = "2"
ITensorPkgSkeleton = "0.3"

[sources.ITensorPkgSkeleton]
path = ".."
