name = "{PKGNAME}"
uuid = "{UUID}"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]
