name = "{PKGNAME}"
uuid = "{UUID}"
version = "0.1.0"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[compat]
julia = "1.10"
